### ISSUE TITLE
【bug】单个任务详细页面，elog不出现任务本身的链接，只出现打开，关闭这些（因为都是在描述当前任务，没必要罗嗦重复），评论输入框也没有分配任务的控件（以上两点均可参考设计图，图是对的）。

### ISSUE THREAD

**Issue by zkuang** [zkuang/laixi-vue#15]

**Comment by JefferyLiang** [comment]
问题1：
在task详细页面里有需要显示什么类型的EventLog？只需要显示打开和关闭还有评论的Log？（我暂时先这样做）

问题2: 是要去掉分配任务的那一块还是要添加一块？（没有评论分配的控，这个描述......我看到是有这个哦空间，我就先把这个控件去掉，因为在任务里面创建任务很奇怪）

**Comment by JefferyLiang** [comment]
由于任务描述对于不知道详细需求的我有点难以描述我尝试根据我的理解去修复了这个BUG

对应的pull request在[这里](https://github.com/zkuang/laixi-vue/pull/25)。

在里面我留下了一些简单的信息。

**Comment by zkuang** [comment]
我印象中有3种post，一种是critique（评论），一种是draft event（关于draft的event，比如创建，修改draft）还有一个钟task event（关于task的修改），draft event 应该是没有的，这个bug是说task event也不需要，只保留creitique。

**Comment by zkuang** [comment]
这个我都不是很清晰，我先问问
