### ISSUE TITLE
【优化】归档操作和UI细节

### ISSUE THREAD

**Issue by zkuang** [zkuang/laixi-vue#16]
1. 为了和其他体验部分保持统一，确认改为 simple modal（全屏遮盖的那种，详见附图）
2. 文案，见附图
3. 按钮名称，见附图
4. 归档一个文件后，跳转至项目的全部归档列表页面。
5. 取消一个文件的归档后，跳转至这个文件的文档详情页面。
![1](https://user-images.githubusercontent.com/2045053/29026927-d251c2ae-7bb0-11e7-8705-6e94f3acc1df.png)
![2](https://user-images.githubusercontent.com/2045053/29026928-d253bcf8-7bb0-11e7-88b6-033f6323cd3b.png)
![3](https://user-images.githubusercontent.com/2045053/29026929-d2546798-7bb0-11e7-941b-69d8fecd2a99.png)

**Comment by JefferyLiang** [comment]
优化的pull request在[这里](https://github.com/zkuang/laixi-vue/pull/27)。

有问题可以在那边留或者这里留。

**Comment by zkuang** [comment]
提示文本不对，但我修复了，剩下delete两次不能恢复文档，似乎是API的问题。
