### ISSUE TITLE
【bug】单个任务详细页面，也应有左侧的修改和删除悬停菜单，点击label也应可以修改负责人和截止时间。

### ISSUE THREAD

**Issue by zkuang** [zkuang/laixi-vue#22]

**Comment by JefferyLiang** [comment]
连接`https://github.com/zkuang/laixi-vue/pull/24`

**Comment by JefferyLiang** [comment]
关于这个BUG的pull requests 在[这里](https://github.com/zkuang/laixi-vue/pull/24)。

在修复这个BUG的时候遇到了一些问题我留在了pull里面。
