### ISSUE TITLE
【优化】创建任务，不离开输入框应可使用回车快捷保存（参考 Tower）。

### ISSUE THREAD

**Issue by zkuang** [zkuang/laixi-vue#9]

**Comment by zkuang** [comment]
【优化】任务时间控件，应为中文。（评估工作量：参考 Tower 添加今天明天本周下周快捷按钮）

**Comment by JefferyLiang** [comment]
这个任务的pull request在[这里](https://github.com/zkuang/laixi-vue/pull/29)

有什么问题可以再留在这个地方
